/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CitizenRouteRouteImport } from './routes/citizen/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficerRouteRouteImport } from './routes/officer/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCctvRouteImport } from './routes/admin/cctv'
import { Route as AdminComplaintsRouteRouteImport } from './routes/admin/complaints/route'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as CitizenIndexRouteImport } from './routes/citizen/index'
import { Route as CitizenDashboardRouteImport } from './routes/citizen/dashboard'
import { Route as CitizenReportRouteImport } from './routes/citizen/report'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as OfficerDashboardRouteImport } from './routes/officer/dashboard'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin/complaints/index'
import { Route as AdminComplaintsIdRouteImport } from './routes/admin/complaints/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CitizenComplaintsIdRouteImport } from './routes/citizen/complaints.$id'
import { Route as OfficerComplaintsIdRouteImport } from './routes/officer/complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRouteRoute = CitizenRouteRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRouteRoute = OfficerRouteRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCctvRoute = AdminCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComplaintsRouteRoute = AdminComplaintsRouteRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRouteRoute,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CitizenRouteRoute,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CitizenRouteRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRouteRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRouteRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminComplaintsRouteRoute,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminComplaintsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenComplaintsIdRoute = CitizenComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => CitizenRouteRoute,
} as any)
const OfficerComplaintsIdRoute = OfficerComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => OfficerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/citizen': typeof CitizenRouteRouteWithChildren
  '/officer': typeof OfficerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/complaints': typeof AdminComplaintsRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/map': typeof AdminMapRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/map': typeof AdminMapRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/citizen': typeof CitizenRouteRouteWithChildren
  '/officer': typeof OfficerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/complaints': typeof AdminComplaintsRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/map': typeof AdminMapRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/report': typeof CitizenReportRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/citizen'
    | '/officer'
    | '/login'
    | '/admin/complaints'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/dashboard'
    | '/admin/map'
    | '/citizen/dashboard'
    | '/citizen/report'
    | '/officer/dashboard'
    | '/admin/'
    | '/citizen/'
    | '/officer/'
    | '/admin/complaints/$id'
    | '/api/auth/$'
    | '/citizen/complaints/$id'
    | '/officer/complaints/$id'
    | '/admin/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/dashboard'
    | '/admin/map'
    | '/citizen/dashboard'
    | '/citizen/report'
    | '/officer/dashboard'
    | '/admin'
    | '/citizen'
    | '/officer'
    | '/admin/complaints/$id'
    | '/api/auth/$'
    | '/citizen/complaints/$id'
    | '/officer/complaints/$id'
    | '/admin/complaints'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/citizen'
    | '/officer'
    | '/login'
    | '/admin/complaints'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/dashboard'
    | '/admin/map'
    | '/citizen/dashboard'
    | '/citizen/report'
    | '/officer/dashboard'
    | '/admin/'
    | '/citizen/'
    | '/officer/'
    | '/admin/complaints/$id'
    | '/api/auth/$'
    | '/citizen/complaints/$id'
    | '/officer/complaints/$id'
    | '/admin/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CitizenRouteRoute: typeof CitizenRouteRouteWithChildren
  OfficerRouteRoute: typeof OfficerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cctv': {
      id: '/admin/cctv'
      path: '/cctv'
      fullPath: '/admin/cctv'
      preLoaderRoute: typeof AdminCctvRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRouteRoute
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof CitizenRouteRoute
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof CitizenRouteRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminComplaintsRouteRoute
    }
    '/admin/complaints/$id': {
      id: '/admin/complaints/$id'
      path: '/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof AdminComplaintsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/complaints/$id': {
      id: '/citizen/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/citizen/complaints/$id'
      preLoaderRoute: typeof CitizenComplaintsIdRouteImport
      parentRoute: typeof CitizenRouteRoute
    }
    '/officer/complaints/$id': {
      id: '/officer/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/officer/complaints/$id'
      preLoaderRoute: typeof OfficerComplaintsIdRouteImport
      parentRoute: typeof OfficerRouteRoute
    }
  }
}

interface AdminComplaintsRouteRouteChildren {
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
}

const AdminComplaintsRouteRouteChildren: AdminComplaintsRouteRouteChildren = {
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
}

const AdminComplaintsRouteRouteWithChildren =
  AdminComplaintsRouteRoute._addFileChildren(AdminComplaintsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminComplaintsRouteRoute: typeof AdminComplaintsRouteRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCctvRoute: typeof AdminCctvRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminComplaintsRouteRoute: AdminComplaintsRouteRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCctvRoute: AdminCctvRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMapRoute: AdminMapRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CitizenRouteRouteChildren {
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CitizenComplaintsIdRoute: typeof CitizenComplaintsIdRoute
}

const CitizenRouteRouteChildren: CitizenRouteRouteChildren = {
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CitizenComplaintsIdRoute: CitizenComplaintsIdRoute,
}

const CitizenRouteRouteWithChildren = CitizenRouteRoute._addFileChildren(
  CitizenRouteRouteChildren,
)

interface OfficerRouteRouteChildren {
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerComplaintsIdRoute: typeof OfficerComplaintsIdRoute
}

const OfficerRouteRouteChildren: OfficerRouteRouteChildren = {
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerComplaintsIdRoute: OfficerComplaintsIdRoute,
}

const OfficerRouteRouteWithChildren = OfficerRouteRoute._addFileChildren(
  OfficerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CitizenRouteRoute: CitizenRouteRouteWithChildren,
  OfficerRouteRoute: OfficerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
